name: nannyplus
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.16.0+9999

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  bloc: ^8.0.3
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  file_picker: ^5.3.1
  firebase_analytics: ^10.4.2
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  #flutter_local_notifications: ^12.0.3
  flutter_form_builder: ^9.0.0
  flutter_localizations:
    sdk: flutter
  #flutter_native_timezone: ^2.0.0
  flutter_riverpod: ^2.3.0
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.2.0
  get: ^4.6.1
  gettext_i18n: ^1.0.5
  google_fonts: ^4.0.4
  grouped_list: ^5.0.1
  http: ^0.13.4
  image_picker: ^1.0.2
  intersperse: ^2.0.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logger: ^2.0.1
  open_file_plus: ^3.3.0
  package_info_plus: ^4.0.1
  path: ^1.8.1
  path_provider: ^2.0.8
  pdf: ^3.8.1
  printing: ^5.11.0
  provider: ^6.0.1
  riverpod_annotation: ^2.0.0
  share_plus: ^7.0.1
  shared_preferences: ^2.0.9
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.2.1+1
  timezone: ^0.9.0
  url_launcher: ^6.0.17

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.0
  riverpod_generator: ^2.0.0
  very_good_analysis: ^5.0.0+1

flutter_native_splash:
  color: "#ffffff"
  image: assets/img/banner1500.png
  color_dark: "#434343"
  image_dark: assets/img/banner1500.png
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "external_assets/launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/img/
    - assets/fonts/
    - assets/google_fonts/
  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
    - family: STCaiyun
      fonts:
        - asset: assets/fonts/STCaiyun.ttf
    - family: Butterfly Kids
      fonts:
        - asset: assets/fonts/ButterflyKids-Regular.ttf
    - family: Fredericka the Great
      fonts:
        - asset: assets/fonts/FrederickatheGreat-Regular.ttf
    - family: Gwendolyn
      fonts:
        - asset: assets/fonts/Gwendolyn-Bold.ttf
    - family: Mystery Quest
      fonts:
        - asset: assets/fonts/MysteryQuest-Regular.ttf
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
    - family: Rampart One
      fonts:
        - asset: assets/fonts/RampartOne-Regular.ttf
